version: '3.7'

services:
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - "6379:6379"
#      - REDIS_PORT=${REDIS_PORT}
    environment:
      - REDIS_PORT=${REDIS_PORT}e
    env_file:
      - ./.env.prod

  email-sender:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: "sender"
    ports:
      - "3000:3000"
#      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
    env_file:
      - ./.env.prod

networks:
  email-sender:
    external: true

x-docker-project-name: email-sender