version: '3.7'

services:
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - "6379:6379"

  email-sender:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: "sender"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}

networks:
  default:
    name: email-sender
    external: true
