version: '3.7'

services:
#  zookeeper:
#    image: wurstmeister/zookeeper:3.4.6
#    container_name: zookeeper
#    ports:
#      - "2181:2181"

#  kafka:
#    image: wurstmeister/kafka:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#
#  rabbitmq:
#    image: rabbitmq:3.8.23-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - "6379:6379"

#  email-sender:
#    build:
#      context: ../
#      dockerfile: docker/Dockerfile
#    container_name: "sender"
#    ports:
#      - "8080:8080"

networks:
  default:
    name: email-sender
    external: true