version: '3.7'

services:
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - "6379:6379"

#  email-sender:
#    build:
#      context: ../
#      dockerfile: docker/Dockerfile
#    container_name: "sender"
#    ports:
#      - "8080:8080"

networks:
  default:
    name: email-sender
    external: true